### PR TITLE
Update ui.json

### PR DESCRIPTION
**Pull request by ltdstudio**
add some chinese translations for Game create menu.  
sorry , this is my frist post. please fix error on line 174 （add ,） and del  ,  on line 206. I'll take more careful next time

### CODE REVIEW

**Review by bafolts — APPROVED** [review]
Perfect! Thank you.

**Comment by ltdstudio** [comment]
Can you allow me to publish terraforming-mars on Docker hub?

Brian Folts <notifications@github.com> 于2020年12月4日周五 上午12:08写道：

**Comment by bafolts** [comment]
I don't know much about docker hub. I don't think you would need permission from me to publish.

**Comment by ltdstudio** [comment]
Cool, thanks!

Brian Folts <notifications@github.com> 于2020年12月4日周五 上午9:10写道：

**Pull request merged**
