### PR TITLE
add no negative turmoil event to setup details

### PR DESCRIPTION
**Pull request by vsrisuknimit**
image

### CODE REVIEW

**Comment by kberg** [comment]
Am I mistaken or are we basically trying to avoid these kinds of changes where the solution is a configurable list of cards?

**Comment by vsrisuknimit** [comment]
@kberg you cannot adjust turmoil event. This is one of the option for Turmoil.
image

**Comment by kberg** [comment]
> @kberg you cannot adjust turmoil event. This is one of the option for Turmoil.
> image

Oh yeah of course. My bad.

**Review by kberg — APPROVED** [review]
Of course. Thank you. Sorry I misread it.

**Pull request merged**
