### PR TITLE
show energy to heat conversion in box background

### LINKED ISSUE #2696: Provide visual cue that heat leads to temperature
Like this?

image

### PR DESCRIPTION
**Pull request by vsrisuknimit**
This close #2696 .

image

### CODE REVIEW

**Comment by kberg** [comment]
What's with the funny unicode on the megacredits production box?

**Comment by vsrisuknimit** [comment]
@kberg I actually have no idea since my code does not touch it. I will look into it.

**Comment by vsrisuknimit** [comment]
image

Don't see it anymore. I have no idea. @kberg

**Comment by vsrisuknimit** [comment]
Do you prefer the example above or this? To show the conversion is on the resource not production. I personally prefer the first one, not this one below.

image

**Comment by sienmich** [comment]
I like the first one more, nice

**Review by sienmich — APPROVED** [review]

**Comment by kevinb9n** [comment]
Agreed, first one looks great. Balanced.

**Review by kberg — COMMENTED** [review]
Fantastic. Nice and clean. & is a piece of CSS I will have to go learn now.

**Comment by kberg** [comment]
Incidentally, I like the second one much, much more. But it's just fine.

**Pull request merged**
