### PR TITLE
Compiller flag to enable incremental builds

### PR DESCRIPTION
**Pull request by alrusdi**
It improves compilation time for consequential builds. I believe it can speed up "cover" step on CI too

### CODE REVIEW

**Review by kberg — APPROVED** [review]
Incremental builds?? Yum!

**Comment by bafolts** [comment]
As far as I know this was already on as `true` is the default.

```
--incremental | boolean | true if composite is on, false otherwise | Enable incremental compilation by reading/writing information from prior compilations to a file on disk. This file is controlled by the --tsBuildInfoFile flag.
```

**Comment by alrusdi** [comment]
Strange. I've found much faster compilation times after this change. Revert it then

**Comment by bafolts** [comment]
I don't think it does any harm being set to `true`. Since `composite` defaults to `true` I am pretty sure it is irrelevant.

**Comment by alrusdi** [comment]
@bafolts have you seen this project https://github.com/pinterest/esprint 
It may speed up eslint little bit

**Pull request merged**
