### PR TITLE
Rounded corners for custom buttons.

### PR DESCRIPTION
**Pull request by kberg**
image

### CODE REVIEW

**Comment by kberg** [comment]
Also make text inside a button translateable.

**Review by Argeento — APPROVED** [review]

**Comment by kberg** [comment]
Pushed too much code, sry.

**Comment by kberg** [comment]
k fixed.

**Comment by Argeento** [comment]
I remind you to write tests - button component had a great cover

**Review by nwai90 — APPROVED** [review]

**Comment by nwai90** [comment]
> I remind you to write tests

This is a visual change which is easily readable and observable so adding tests for this particular change is not worth the effort imo. @Argeento Is there a specific test case you have in mind here? e.g. asserting the presence of a class, i18n or something else?

**Comment by Argeento** [comment]
The class. Adding this case to existing tests should take no longer than two lines of code.

Yes, this test is not necessary. I accepted this PR before.

**Pull request merged**
