### PR TITLE
Add Moon MAs

### PR DESCRIPTION
**Pull request by kberg**
**Note:** Baseline is PR 2908

### CODE REVIEW

**Comment by vsrisuknimit** [comment]
Once you are all done with the Milestones and Awards change, can we rerun the test on the randomizer distribution? Just for sanity check.

Randomize with Venus, without Venus, with Moon, or with Ares.

**Comment by kberg** [comment]
Actually -- we should do it **before.** A couple of observations during
development makes me nervous that I broke it, but didn't think about how to
deal with it, and that's exactly how - thanks.

**Comment by kberg** [comment]
Ha! Not yet:

image

**Comment by kberg** [comment]
Ah, fixed. A simple issue about naming.

image

**Review by bafolts — APPROVED** [review]

**Comment by bafolts** [comment]
I :heart: this chart.

**Comment by kberg** [comment]
> I  this chart.

Yeah, it's nice. More charts. I want more charts.

**Pull request merged**
