### PR TITLE
Colonies fixes

### PR DESCRIPTION
**Pull request by chosta**
@alrusdi 
I will work on colonies vusual fixes for the new icons and let you know when ready
[do not merge]

### CODE REVIEW

**Comment by chosta** [comment]
@nwai90 @alrusdi should be ready for merge

**Comment by chosta** [comment]
@nwai90 please, remove the do not merge label, it is ready to reviewed / merged

**Comment by alrusdi** [comment]
Can you merge it with current master branch and check if everything alright?

**Comment by chosta** [comment]
No issues on a first glance. Checked all colonies and played 2 rounds. We'll see how this goes in gameplay.

**Review by alrusdi — APPROVED** [review]
Let's merge it then

**Pull request merged**
