### PR TITLE
DRY and cleanup all tests except Turmoil

### PR DESCRIPTION
**Pull request by nwai90**

### CODE REVIEW

**Comment by alrusdi** [comment]
@nwai90 there are failing tests. Are they related to this changes?

**Comment by nwai90** [comment]
> @nwai90 there are failing tests. Are they related to this changes?

I had a look. It seems that some tests are flaky when running on CI, although they pass locally. Examples:

- Turmoil.spec.ts
- LavaFlows.spec.ts
- LavaTubeSettlement.spec.ts

**Comment by nwai90** [comment]
@alrusdi I fixed it by adding a function to reset the board across tests, but I think the intermittent test failures are worth a relook (especially for Turmoil). Not sure if it is related to config or other causes. Do you know if the tests are running in parallel on CI?

**Comment by alrusdi** [comment]
I don't think if they are run in parallel. But some problems is there. And i am experiencing them from time to time on localhost too.

**Pull request merged**
