### PR TITLE
Player name color and style adjustments

### PR DESCRIPTION
**Pull request by FreeLikeGNU**
These are some tweaks to make the player names (and highlighting) more readable in turn order and log.

Screenshot_2020-03-27_14-47-14

### CODE REVIEW

**Comment by FreeLikeGNU** [comment]
I can't seem to get the Heading (title and player name) color to use the colors defined in player_home.less.

**Comment by alrusdi** [comment]
> I can't seem to get the Heading (title and player name) color to use the colors defined in player_home.less.

You can move them out of player_home_block in player_home.less or define color values somewhere like colors.less as variable and then reuse them in your definitions

**Comment by FreeLikeGNU** [comment]
Screenshot_2020-03-28_00-40-29

**Comment by FreeLikeGNU** [comment]
This is ready for review @alrusdi  Thank you for your time!

**Comment by FreeLikeGNU** [comment]
tossing this one in the bin...

**Pull request closed without merging**
