### PR TITLE
Make Luna Ecumenopolis not playable unless player can place 2 colonies.

### PR DESCRIPTION
**Pull request by kberg**
This was surprisingly easier than I expected. What am I missing?

The algorithm takes into account the possibility that the first
colony placed is necessary to place to second colony.

### CODE REVIEW

**Comment by kberg** [comment]
Fixes #3655

**Comment by bafolts** [comment]
Wow what a complex card!

Do the two placed tiles need to be adjacent?

Each of these tiles then needs to be adjacent to two other colony tiles which are already on the board?

**Comment by kberg** [comment]
> Wow what a complex card!
> 
> Do the two placed tiles need to be adjacent?

No, it's just an implied effect that the first placed tile can often be a basis for the second-placed tile.

> 
> Each of these tiles then needs to be adjacent to two other colony tiles which are already on the board?
I think the answer above clarifies that this is not the case.

**Comment by kberg** [comment]
See, it's not a complex card if you're looking at a real board in front of you.

**Review by bafolts — APPROVED** [review]

**Comment by bafolts** [comment]
This is elegant solution.

**Pull request merged**
