### PR TITLE
OCD fixes

### PR DESCRIPTION
**Pull request by chosta**
These things were bothering my OCD:
1. MAX button is misaligned
krivo

2. Colony selected marker covered the title of colonies with longer names. And was unappealing as a whole. The proposed solution includes an opacity with the linear gradient and some height and positioning adjustments:
ganymede

Please, review only this in `colinies.less` the other is formatting:
`input[type="radio"]:checked + .colonies::after {
    top: 17px;
    left: 174px;
    width: 251px;
    background: linear-gradient(
       to right,
        rgba(226, 140, 34, 0.1),
        #e28c22,
       #c97e23
    );
    height: 47px;
border-bottom: none;
 }`

### CODE REVIEW

**Review by nwai90 — APPROVED** [review]

**Comment by alrusdi** [comment]
@chosta merge the upstream master please

**Comment by chosta** [comment]
@ssimeonoff is no border a desired behaviour? Not sure how I feel about it.
no background

**Comment by ssimeonoff** [comment]
There is no border , but there is a box shadow in another PR.

**Comment by ssimeonoff** [comment]
I pushed a typo! facepalm
@chosta , fix it in this pr:
"inset 0 0 fpx 4px...." to "inset 0 0 4px 4px ...." for all 11 colonies

**Comment by chosta** [comment]
> inset 0 0 fpx 4px

you need proper linting that's what you need :)
but also my linter didn't catch it so IDK

**Pull request merged**
