### PR TITLE
Added "Toggle all" button to debug-ui making it easier to focus on one expansion.

### PR DESCRIPTION
**Pull request by kberg**
I know the button is boxy. Since this is a debug-only UI, this is probably good enough.

### CODE REVIEW

**Comment by kberg** [comment]
I added a fix to an irritating bug.

**Review by alrusdi — COMMENTED** [review]
package-lock.json is unrelated to this PR. Did you mean to change it?

**Comment by kberg** [comment]
> package-lock.json is unrelated to this PR. Did you mean to change it?

Sorry, I thought I got rid of it. I'll either close this and star fresh, or see if I can fix it.

**Comment by kberg** [comment]
> > package-lock.json is unrelated to this PR. Did you mean to change it?
> 
> Sorry, I thought I got rid of it. I'll either close this and star fresh, or see if I can fix it.

That was simple. Thank you, stackoverflow.

**Review by alrusdi — APPROVED** [review]

**Pull request merged**
