### PR TITLE
Adding global parameters indicator

### PR DESCRIPTION
**Pull request by vsrisuknimit**
Indicator for global parameters on the side bar.

Without Venus.

image

With Venus.

image

@ssimeonoff please help.

### CODE REVIEW

**Comment by vsrisuknimit** [comment]
- Zoom out works fine. Zooms in too closely make the number move weirdly, but at that zoom level, the side bar misbehaves anyway (you cannot see the colony or card buttons).
- The number is currently clickable as <slot></slot> is under cards button. I don't know how to fix it, sorry.
https://github.com/bafolts/terraforming-mars/blob/eb5afa1ff456db55baebcdc059a3526301309761/src/components/Preferences.ts#L115-L118

**Comment by vsrisuknimit** [comment]
I would like to hide the Venus icon if Venus is not in play. Not sure how to do that since I have that information in Playerhome.ts but not in Preferences.ts where the image is called.

**Review by alrusdi — CHANGES_REQUESTED** [review]
Why do we need an additional image?
All images are already in assets/global-parameters and in tiles/

**Comment by chosta** [comment]
@alrusdi I will help @vsrisuknimit with this one in a private session.

**Comment by alrusdi** [comment]
> Also I'm not digging how wide the sidebar is becomming
I think @ssimeonoff already made it big enough to fit global params

**Comment by ssimeonoff** [comment]
Now I see why you needed those margin-top for the param values :)

I will fix it. Currently the global values are rendered into the cards , instead of being passed as props to Preferences.

**Comment by ssimeonoff** [comment]
Untitled
Changes: 
- SideBar reduced back to 60px width
- Venus param not shown when Venus is not in play
- The chosen order for the params follow the main map layout: top - Venus, bottom: oceans)

**Review by alrusdi — APPROVED** [review]
Great!

**Pull request merged**
