### PR TITLE
StealResources didn't run callback for solo games.

### PR DESCRIPTION
**Pull request by kberg**

### CODE REVIEW

**Review by bafolts — APPROVED** [review]
This change will enable someone to steal from themselves in a solo game. In a multi-player game a player will not be able to steal from themselves as the execute function still filters to only other players. Along with this change it would make sense to me to allow someone to steal from themselves in multi-player games as well as solo games.

**Comment by kberg** [comment]
> This change will enable someone to steal from themselves in a solo game.

How does it do that? (FYI In solo games players steal from the neutral player.)

**Comment by kberg** [comment]
> > This change will enable someone to steal from themselves in a solo game.
> 
> How does it do that? (FYI In solo games players steal from the neutral player.)

Also, this only impacts the card Ancient Shipyards.

**Comment by bafolts** [comment]
I forgot about the neutral player.

**Pull request merged**
