### PR TITLE
Fix argument order for canAfford

### PR DESCRIPTION
**Pull request by Lynesth**

### CODE REVIEW

**Comment by Lynesth** [comment]
@bafolts This is currently "game breaking".
Windows test failed for some reason though.

**Comment by vsrisuknimit** [comment]
#2631

**Review by nwai90 — APPROVED** [review]

**Comment by kberg** [comment]
Given that this fixes a big bug, something deserves a unit test somewhere.

**Comment by Lynesth** [comment]
Actually it would be simple tests with different cards and different resources and then just check that player.canPlay(card) returns the correct value.

Will try to do that today.

**Pull request merged**
