### PR TITLE
Confirm plants conversion before placing Greenery

### PR DESCRIPTION
**Pull request by Lynesth**
This makes the behavior more consistent. You have to validate before placing a tile when you select the Aquifer/Greenery/City standard projects. It also alleviates the issue described here: https://github.com/bafolts/terraforming-mars/issues/1240

### CODE REVIEW

**Comment by nwai90** [comment]
@Lynesth Can you make it an option that is off by default? This slows down the game

**Comment by Lynesth** [comment]
There is no communication between in-browser player preferences and the server, so that is not an option at the moment, no.

**Comment by kberg** [comment]
It's such a weird case, that's for sure.

**Comment by Lynesth** [comment]
I get that different people, depending on their experience with the app, would most likely prefer one thing or the other.
It's just that it's the only action that actually validates when clicking the map, instead of having to click a button like every other.

I often find myself pondering, then I pick "Convert plants" and click "Save". The app tells me I need to select a space so I scroll up and click the map. The save button is actually useless but if you removed it then it wouldn't make sense when selecting that option.

Anyway, just my opinion on this. I'm sure if we take a bit of time we can use the preferences server side as well but that's something I guess needs more discussion.

**Comment by kberg** [comment]
A data point: if this was something that impacted several minutes per game, I'd be more concerend. But given that this happens at ~20 times in a game around 95% of the time, compared to the many, many more clicks, I'm not quite suire this is the the hill to die on for performance over consistency.

But I can live with it. Also, https://xkcd.com/1172/

**Comment by alrusdi** [comment]
I think we need more general solution to confirm all the tile placements and it MUST be optional

**Comment by Lynesth** [comment]
Just to make it clear, it is not a confirmation of tile placement, like it was proposed in the linked issue.
It's just 1 click to say: "The action I want to take is `Convert plants to greenery`" and then place the tile.

**Comment by kberg** [comment]
What's blocking this from proceeding?

**Comment by alrusdi** [comment]
> What's blocking this from proceeding?

At least two of us (me and @nwai90) want it to be optional. If it can't be optional - we should reject this PR

**Comment by Lynesth** [comment]
> If it can't be optional - we should reject this PR

Well there's currently no way to make this optional as I mentioned.

But I don't understand, it is the only action that doesn't require a click. Everything else does.
Are you two saying that the fact that you have to click to confirm you want to use an Aquifer/Greenery/City standard project instead of just placing the tile directly slows the game ? (genuine question)

**Comment by alrusdi** [comment]
I think a lot of confirmations really slows the game and they are very annoying. 
What a problem to pass user preferences to the server btw? It can be a great start to persist them in DB later.

**Comment by Lynesth** [comment]
> I think a lot of confirmations really slows the game and they are very annoying.

If actions were buttons from the start (like what @ssimeonoff proposed here https://github.com/bafolts/terraforming-mars/issues/953) then there wouldn't be a problem since eveything would be consistent.
The issue at the moment is that we have a radio menu with submenus and that the only one that doesn't behave like the others is the plant conversion. I mean, when it's your turn, you don't even have to go down to the actions, you can click on the map to put a greenery (issue raised in #1240) and that's seems pretty inconsistent to me.

> What a problem to pass user preferences to the server btw?

There's no problem with that, and it should be done at some point, I agree. It's just that it isn't possible at the moment and that's why it's not a possibility for the current PR.

**Comment by alrusdi** [comment]
If we have an option to fix that issue by action button redesign (and we will do it at some point) then why so urgent to fix the greenery placement right now?

**Comment by kberg** [comment]
> I think a lot of confirmations really slows the game and they are very annoying.

So @alrusdi I'm not actually going to try to say that this change should go in, but I also think your reasons for keeping this out are not that hard to dispute. Given that the number of greeneries placed in a game, as a ration of all the clicks and actions, are so small that this isn't a meanignful time change.

Greenery placement is the only specialty behavior that optimizes out the step where I have to tell the app that I'm placing a greenery tile. As an outlier, I personally found it difficult to understand, only until after about 20-30 games. (I played a LOT of ground solo games with Ares, as you can imagine.)

I don't think anyone can disagree with "a lot of conformations really slows the game and they are very annoying" as a general complaint, but relatively speaking I just don't think this is that. So I assume you really mean that you want to avoid death-by-a-thousand-cuts.

But this specialty behavior, well, it's _distinct_ and _surprising._ And as UX goes, distinct and surprising isn't good.

But I am not here to set a new direction for the game's UX.

**Comment by alrusdi** [comment]
I'm not against it if it will be optional

**Comment by kberg** [comment]
I'm pleased to read that. Also, I'm unhappy because now I have to go read the details about why it can't be optional. Baby steps, I suppose. :D

**Comment by kberg** [comment]
OK, so: what would it take to actually support this?  Let's start with an awful hack and call it the worst suggestion that works.

### The worst suggestion so far
* Add `GetUserPreferences extends PlayerInput`, which returns a dictionary of the player's preferences without actually requesting input.
* Use `GetUserPreferences` in `convertPlantsIntoGreenery`.
* The callback will evaluate whether to return a `SelectSpace` or `SelectOption` `PlayerInput` instance.

**Comment by alrusdi** [comment]
We can add an endpoint like /sync-preferences and save current user preferences in the Player instance. It can be done at the start of the game. That preferences can be used to check if confirmation of the greenery placement needed. Later we can persist preferences in DB with player account

**Comment by kberg** [comment]
And by syncing if decide part-way through the game to toggle that preference it'll update it? Yeah, perhaps.

What if it didn't actually persist it? Just keep it in memory, and if the instance restarts it asks for a new ... no, that won't work. ... Hmm... would the server-side be the definitive place for user preferences?

**Comment by alrusdi** [comment]
> Hmm... would the server-side be the definitive place for user preferences?
It should. But we don't have an account/profile entity yet to store preferences with it.

**Comment by kberg** [comment]
> > Hmm... would the server-side be the definitive place for user preferences?
> 
> It should. But we don't have an account/profile entity yet to store preferences with it.
> Client can switch devices/browser, but preferences should remain the same (some of them at least :-) )

Since there's no plans for user login, let's go back to the original suggestion which fetches options upon request. Any strong objections to making it work that way?

**Comment by bafolts** [comment]
I think the suggestion in #1240 makes more sense than having to click twice prior to placing the tile altogether. The issue in #1240 would still remain but the confirmation would happen prior to `SelectSpace`. Updating `SelectSpace` to require clicking a button prior to selecting the space should be possible. We could have double click work as a stop gap to place the tile without require finding the button to click to confirm. Upon clicking to "Convert Plants" we could scroll up and bring the board into focus as you will need to click there. I would consider how `SelectSpace` would work best versus attempting to make the current `SelectSpace` less confusing. Scrolling the user up to the board could go a long way for the time being. It should lead to a faster game and be same number of clicks while avoiding confusion around needing to select a space on the board.

**Comment by bafolts** [comment]
How about, when `SelectSpace` is triggered we bring the board into focus for mobile users or users on smaller screens. At this point you have to select a space. Upon clicking once the tile is placed on the board. Next to the tile is a tooltip like "Save". If you click again you can move the tile location and the "Save" button is still right by the tile. If you double click instead of click the tile is placed as before with no confirmation.

**Comment by kberg** [comment]
To me, @bafolts the issue is that in order to Do Anything, you have to start with the OrOptions widget, _except_ place greenery. Eliminating that outlier, in my opinon, is preferable. I wouldn't have any issue with *two* confirmations. But that's me - I'm not playing Speed Terraforming Mars. :D

**Comment by nwai90** [comment]
> How about, when `SelectSpace` is triggered we bring the board into focus for mobile users or users on smaller screens. At this point you have to select a space. Upon clicking once the tile is placed on the board. Next to the tile is a tooltip like "Save". If you click again you can move the tile location and the "Save" button is still right by the tile. If you double click instead of click the tile is placed as before with no confirmation.

The current implementation favours convenience in that `SelectSpace` is immediately triggered if the player had enough plants to place a greenery, without the need for any additional clicks beyond placing the greenery tile on the board. The above approach could work and is the gist of https://github.com/bafolts/terraforming-mars/issues/497. Ideal scenario would be to eventually introduce an option to enable/disable these in-game confirmations so that they are optional for the user as @alrusdi has mentioned.

**Comment by bafolts** [comment]
Ah, I now understand what this solution is going for within `OrOptions`. For what it's worth. The current `SelectSpace` happened to be the easiest to implement when I was writing this way back when. If I assume the speed players are playing single player games could consider only enabling this for games with more than one player. This wouldn't interrupt the single player games and would avoid requiring an option.

**Comment by Lynesth** [comment]
I can understand that some of you prefer the way it is currently implemented but it seems you don't think this is bad UX.
Let's try to be impartial here and realize that:
- That action is the only one that doesn't behave like the others
- It presents a `Save` button that does nothing
- It gives the player the risk to make an error by simply clicking/tapping on the map if that option is selected

Also I want to make clear that I am not in favour of a "confirm all tile placement" system, except if that's optional.
I am just talking about reducing errors while making available actions consistent.

Why not make a poll on discord to collect players' opinion on this ?

**Comment by chosta** [comment]
> * It presents a `Save` button that does nothing

This is very confusing I must admit.
I feel that this conversation is not making progress as it's obvious there are different opinions and not a single correct solution to the problem.
My take on this is -> keep the current implementation -> get rid of the `Save` button (if possible) -> think of a better general UX solution (me and @ssimeonoff can work on that)

**Comment by kberg** [comment]
The error message that accompanies the Save button failure is the very
thing that allowed me to know how to place a greenery in the first place.
Please keep it until a better change is in place.

**Comment by chosta** [comment]
I was thinking about this as I got burned the other day by not placing on the corect hex the other day. It was on my mobile phone and you to be very nifty to perform this operation. I failed ofc and probably lost the game. I also understand why we would not want it when playing on desktop and using timers etc. So for me the solution should be: Add an option to have a warning / or not and let the players decide. On mobile I would 100% use it and on desktop 100% not.

**Pull request closed without merging**
