### PR TITLE
[WIP] Kickstarter bigbox promos

### PR DESCRIPTION
**Pull request by nwai90**
**Ref:** https://www.kickstarter.com/projects/strongholdgames/terraforming-mars-big-box

Three new promo cards that will **replace** existing cards in the game. Waiting for more information about full card details as the current reveals are very limited.

Confirmed so far:
- All 3 cards will place tiles
- Deimos Down promo removes 6 plants instead of 8
- Great Dam promo cost increased to 15
- Magnetic Field Generators promo cost increased to 22

Screenshot 2020-06-17 at 9 19 02 AM

### CODE REVIEW

**Comment by vincentneko** [comment]
Impressive !

**Comment by vincentneko** [comment]
Let's create a specific branch for this so we can work together on it.

**Comment by vincentneko** [comment]
@alrusdi Could you please create 3 new tiles for the promo cards ?

**Comment by alrusdi** [comment]
@vincentneko yes, i will do it today. I have a questions about cards markup too. We are probably need some kind of styleguide

**Comment by nwai90** [comment]
Saw a preview of the new tiles here:

Screenshot 2020-06-19 at 2 22 49 PM

**Comment by alrusdi** [comment]
@vincentneko done

**Comment by vincentneko** [comment]
> @vincentneko done

@alrusdi 
Nice tiles, thanks !

**Pull request merged**
