### PR TITLE
ma rework

### PR DESCRIPTION
**Pull request by ssimeonoff**
TODO: @chosta 
ma

- one button "Milestone Awards" toggle both
- display  3 "ghost" milestones and awards (grey background) 
- claimed/ghost milestones/awards are on two rows on right from the Ma button
- claimed milestone and awards are displayed with their own partial background (awards one is thinner with border-radius)

### CODE REVIEW

**Comment by chosta** [comment]
@ssimeonoff On it

**Comment by alrusdi** [comment]
@ssimeonoff will new captions on MAs be translatable?

**Comment by ssimeonoff** [comment]
Of course not. If you want them, then the eye candy should be removed (the backgrounds)

**Comment by chosta** [comment]
@ssimeonoff I haven't. Probably not today and tomorrow too.

**Comment by alrusdi** [comment]
@ssimeonoff if you give me an images without the captions and a font for award captions i can do everything else. Then @chosta and you will validate my work

**Comment by chosta** [comment]
@alrusdi feel free to do it

**Comment by ssimeonoff** [comment]
After revising the above design, reverted some ideas and went for a cleaner UI
Current one is:
Desktop and mobile with collapsed and expanded:
Desktop:


Mobile: 



The only UX problem that remains is that on Mobile the milestone/awards buttons are still small.
It will be much better to have this:


But if you guys are ok with that "problem", then just review the PR as it is.

**Comment by chosta** [comment]
I Like!

**Comment by ssimeonoff** [comment]
There isn't space for 5 either - intentional. the majority of games are 2-4 players.

**Comment by chosta** [comment]
@ssimeonoff so we just write off the 5+ player games :/  ?
We'll just have an extra class for it

**Comment by alrusdi** [comment]
May be just spawn 5th and 6th on new line?

**Comment by ssimeonoff** [comment]
5th and 6th and displayed on a 2nd line now, yes.

**Comment by chosta** [comment]
Please, 

+ increase the space between the Milestones and Awards block for lower resolutions.
+ decrease space between rows of player markers for 5+ player games 

vertical

**Comment by chosta** [comment]
Suggestion:
When opening the milestones or awards block, the title container takes the whole width and center the text. Make sure you make the <a /> tag take the full width of the ma-title so toggling works on the whole area.
`"background: #303030;
            border-radius: 8px;
            margin-bottom: 8px;
            text-align: center;"`
center

**Comment by chosta** [comment]
More space between Milestones and board:
not inaff

**Comment by ssimeonoff** [comment]
1. Can increase the margins between the block, but only with few pixels - the width limitation is the width of the payerboard on mobile. 
2. Better to accept the "issue" and make the numbers thinners so the 5th(or 6th) fits on the same row as it were
3. Expanding the MA should NOT make the buttons bigger - this area is already used for claimed m/a

**Comment by chosta** [comment]
> 3. Expanding the MA should NOT make the buttons bigger - this area is already used for claimed m/a
Agree


Shouldn't unfunded awards also have reduced opacity once all are funded?

hide

**Comment by chosta** [comment]
@ssimeonoff great work once again. These are really slick (apart from scientist and landlord images but you know it already)

**Comment by ssimeonoff** [comment]
Untitled

It fits 5 now. (if you really want it to fit 6 then just reduce the width from 24px to 20).
Claimed milestones are right below the oceans count. 
More padding between them is no needed, because at 50% zoom, they are still looking ok and when there are 6, the width is already bigger than the mobile width (putting the 6th on a 2nd row)

**Review by chosta — APPROVED** [review]

**Comment by alrusdi** [comment]
@ssimeonoff so what about bg images without text to be able translate the widget to other-than-english languages?

**Comment by ssimeonoff** [comment]
Images are not created by me. Even if an image portrays a text in English, the description can be in the desired language, which is enough I think.

**Comment by chosta** [comment]
I think this can be merged as it is and we can think about localization later. Maybe pull to your local just in case for another check @alrusdi

**Comment by alrusdi** [comment]
I don't like it. 
1) Even on relatively wide screens it takes two lines
2) Hoverlord venus icon is strangely cut
3) Awards font barely readable
4) Labels on awards and milestones are not translatable

Why it is better than current version?

**Comment by chosta** [comment]
> 1. Even on relatively wide screens it takes two lines
I agree on this but am 50/50 since we do need more verticle space

> 2. Hoverlord venus icon is strangely cut
Also scientist + landlord could be improved

> 3. Awards font barely readable
> 4. Labels on awards and milestones are not translatable
Maybe we just replace it with text - that would help localization too

> Why it is better than current version?
I think it's a visual improvement. And with just a bit of polish could be really good.

**Comment by ssimeonoff** [comment]
Untitled
If images are cut even more, the real text can be displayed below. (less eye-candy but more functional)

**Review by alrusdi — APPROVED** [review]

**Pull request merged**
