### PR TITLE
Allow undo action for every action of remainning player if all other players passed

### PR DESCRIPTION
**Pull request by alrusdi**

### CODE REVIEW

**Comment by nwai90** [comment]
@alrusdi There is some problem with it, the active player seems to not be able to pass

Screenshot 2020-09-18 at 5 35 17 PM

**Comment by alrusdi** [comment]
> @alrusdi There is some problem with it, the active player seems to not be able to pass
> 

Yep, logic was incorrect. Can you please take another look at it?

**Comment by vincentneko** [comment]
> > @alrusdi There is some problem with it, the active player seems to not be able to pass
> 
> Yep, logic was incorrect. Can you please take another look at it?

This part of the app is very tricky. I would advise extreme caution if we make some changes.

**Comment by alrusdi** [comment]
Let's reject it then

**Comment by vincentneko** [comment]
> Let's reject it then

Not necessarily but maybe we should deploy on a test server

**Pull request closed without merging**
