### PR TITLE
Remove Cards.ts

### PR DESCRIPTION
**Pull request by nwai90**

### CODE REVIEW

**Review by kberg — CHANGES_REQUESTED** [review]
Why? I put there to be used, not to be removed. Could you explain more, please?

**Comment by nwai90** [comment]
@kberg These are minimally used and for very common Javascript functions. They also seem to be used mainly in tests - in which case they should be in `TestingUtils` if at all imo

**Comment by kberg** [comment]
> @kberg These are minimally used and for very common Javascript functions. They also seem to be used mainly in tests - in which case they should be in `TestingUtils` if at all imo

They're minimally used because I just introduced them, like, a week ago, and they can be used elsewhere.

**Comment by Lynesth** [comment]
I'm not saying we shouldn't use shorthand functions, but I'll have to agree with @nwai90 on this specific one though.

Those 2 are only turning
`(card) => card.name === ###` into `Cards.byCardName(###)`
and
`(card) => card.name` into `Cards.toCardName`

Their initial version is already easily readable/understandable, especially the second one.

For the first one (byCardName), a shorthanded version could be used I assume, but then I would probably do it like this instead:
`(card) => card.is(###)`

**Comment by kberg** [comment]
> I'm not saying we shouldn't use shorthand functions, but I'll have to agree with @nwai90 on this specific one though.
> 
> Those 2 are only turning
> `(card) => card.name === ###` into `Cards.byCardName(###)`
> and
> `(card) => card.name` into `Cards.toCardName`
> 
> Their initial version is already easily readable/understandable, especially the second one.
> 
> For the first one (byCardName), a shorthand version could be used I assume, but then I would probably do it like this instead:
> `(card) => card.is(###)`

Well, OK. @nwai90 mind if I restore the branch and apply the changes you proposed?

**Comment by nwai90** [comment]
Sure go ahead

**Review by kberg — APPROVED** [review]

**Pull request merged**
