### PR TITLE
more brazilian portuguese translations

### PR DESCRIPTION
**Pull request by sauloachkar**

### CODE REVIEW

**Comment by alrusdi** [comment]
Too many merges... I want this PR to be more clear.

**Comment by bafolts** [comment]
I agree with @alrusdi . If we are lucky and someone clicks to "Squash and merge" this will end up as one squashed commit. If someone merges this without clicking "Squash and merge" all 25 of these commits will go to the `main` branch. @sauloachkar can you rebase this to one commit?

**Comment by sauloachkar** [comment]
I see. I've only changed files on the locale/br folder.
Is there a way do "clean" my fork?
Should i made it on a branch? Or maybe start a new fork?
(I'm new to this, sorry about the mess)

**Comment by alrusdi** [comment]
> I see. I've only changed files on the locale/br folder.
> Is there a way do "clean" my fork?
> Should i made it on a branch? Or maybe start a new fork?
> (I'm new to this, sorry about the mess)

It is better to make new PR. Copy contents of your locale/br folder to safe location. Checkout main branch and pull the changes from upstream. Make new branch for new PR and copy saved content to locale/br

**Pull request closed without merging**
