### PR TITLE
Fix: Celestic should be able to draw any card with floater icon(s)

### PR DESCRIPTION
**Pull request by nwai90**
Ref: https://github.com/bafolts/terraforming-mars/issues/792

### CODE REVIEW

**Comment by nwai90** [comment]
> I'm afraid this one will not work. `resourceType` main purpose is to indicate that the card is able to hold tokens for this type of resource. Adding this property to other cards may have some side effects, like appearing in list where they could receive a resource for instance.
> 
> I think a simple approach is to create an enum of floater related cards (other cards than resourceType Floater) and add them to the Celestic test.

I see, will make the change to go with this approach then

**Comment by vincentneko** [comment]
I think the list is missing 8 cards.
I've used https://ssimeonoff.github.io/cards-list with floater filter to get the list.

Maybe the enum should only list cards that do not have resourceType as floater and the test could be something like :

if (Celestic.floaterCards.has(card.name) || card.resourceType === ResourceType.FLOATER) {

**Comment by nwai90** [comment]
> I think the list is missing 8 cards.
> I've used https://ssimeonoff.github.io/cards-list with floater filter to get the list.
> 
> Maybe the enum should only list cards that do not have resourceType as floater and the test could be something like :
> 
> if (Celestic.floaterCards.has(card.name) || card.resourceType === ResourceType.FLOATER) {

Will update. Where's the floater filter though? Could not find it on the page

**Comment by vincentneko** [comment]
> > I think the list is missing 8 cards.
> > I've used https://ssimeonoff.github.io/cards-list with floater filter to get the list.
> > Maybe the enum should only list cards that do not have resourceType as floater and the test could be something like :
> > if (Celestic.floaterCards.has(card.name) || card.resourceType === ResourceType.FLOATER) {
> 
> Will update. Where's the floater filter though? Could not find it on the page

Just type floater in the "Search by text..." field =)

**Comment by nwai90** [comment]
> > > I think the list is missing 8 cards.
> > > I've used https://ssimeonoff.github.io/cards-list with floater filter to get the list.
> > > Maybe the enum should only list cards that do not have resourceType as floater and the test could be something like :
> > > if (Celestic.floaterCards.has(card.name) || card.resourceType === ResourceType.FLOATER) {
> > 
> > 
> > Will update. Where's the floater filter though? Could not find it on the page
> 
> Just type floater in the "Search by text..." field =)

All good, done!

**Pull request merged**
