### PR TITLE
Better version and deploy date visuals on start screen

### PR DESCRIPTION
**Pull request by alrusdi**

### CODE REVIEW

**Comment by kberg** [comment]
LG, I'm going to leave this for someone else to review, though.

**Comment by alrusdi** [comment]
> LG, I'm going to leave this for someone else to review, though.
Do you need demo to check out visuals?

**Comment by kberg** [comment]
How about just a screenshot?

**Comment by alrusdi** [comment]
> How about just a screenshot?

Demo http://37.230.117.156:9000/

Снимок экрана от 2020-11-24 18-49-09

**Review by kberg — APPROVED** [review]
Thanks!

**Pull request merged**
