### PR TITLE
Layout improvement

### PR DESCRIPTION
**Pull request by rzulian**
I've did something wrong and Improved player layout #472 didn't come through

### CODE REVIEW

**Comment by rzulian** [comment]
@alrusdi could you please merge this?

**Comment by alrusdi** [comment]
> @alrusdi could you please merge this?

I'm sorry i still don't agree with suggested otherPlayer position. I think @bafolts or @vincentneko should do their review

**Comment by rzulian** [comment]
My preference is to have control of the board and my cards, and if needed to scroll down to see other players. In the current layout I have to scroll everything from boar to my cards, because in between there are the others. But again, is my usability preference.

**Comment by FreeLikeGNU** [comment]
I'd love for blocks to be moveable to a players preference.  Implemented with something like https://mauricius.github.io/vue-draggable-resizable/?path=/story/basic--basic-component-with-form-inside

**Comment by rzulian** [comment]
I'm still thinking that the best solution for the playability is to have on hand the most used sections (i.e the board, the log, your board and cards on hand). @alrusdi : if you don't like it, can we at least think to make it an option?

**Comment by alrusdi** [comment]
> I'm still thinking that the best solution for the playability is to have on hand the most used sections (i.e the board, the log, your board and cards on hand). @alrusdi : if you don't like it, can we at least think to make it an option?

1. I like the part with events cards. If you provide it in separate PR - we will accept it immediately
2. Do you have good idea of how to implement optional block positions without copypasting the blocks?

**Comment by rzulian** [comment]
@alrusdi I've reverted the layout changes. Now there is only the event card for the other players

**Pull request merged**
