### PR TITLE
Revert "DX improvements (#3582)"

### PR DESCRIPTION
**Pull request by kberg**
This reverts commit 3f96ac9218280cd5ac0ccbda5546a6ef4b8cfb6e.  It also reverts the change that tests files in tests/* but one thing at a time.

### CODE REVIEW

**Comment by kberg** [comment]
Setting DNM for the moment.

**Review by bafolts — COMMENTED** [review]
There are a variety of ways to do this building and testing code. We could spend most of our time changing this to use new tools. I had approved the change originally as it seemed to run `ts-` more than relying on javascript first being built. I felt this might be easier for new contributors to work with. After this is reverted are there plans to introduce it again? I don't think there is a perfect solution for how all of this is built and tested but I do think what we had is good enough.

**Comment by kberg** [comment]
Oh absolutely we should restore this. In fact, I'd want to start restoring
a couple of these commands immediately, one at a time.

The problem is I'm losing my productivity in terms of debugging, and
spending more time fighting with the development environment than writing
code. This would be short-term only.

But I put the Do Not Merge tag on it, so I can try one more thing.

**Comment by kberg** [comment]
Thanks to @Argeento, I've added the correct configurations to https://github.com/bafolts/terraforming-mars/wiki/Working-with-VSCode which are compatible with these new commands, so I'm closing this PR. Sorry about the fire drill.

**Pull request closed without merging**
