### PR TITLE
[WIP] Ukrainian translation

### PR DESCRIPTION
**Pull request by ainokna**
Opening a WIP pull request for **Ukrainian translation**.
It covers the **base game** and the **Prelude** expansion.
Will work on it together with friends over the next 2-3 weeks.

**Main menu [Before]**
Screen Shot 2021-02-01 at 11 20 43 PM

**Main menu [After]**
Screen Shot 2021-02-01 at 11 20 10 PM

### CODE REVIEW

**Comment by bafolts** [comment]
Awesome! I don't speak the language but can check that everything is in the right place. So far looks like you are on the right track.

**Comment by ainokna** [comment]
1. **[done]** src/locales/ru/base_corporations.json
2. src/locales/ru/cards.json
3. src/locales/ru/colonies_cards.json
4. src/locales/ru/colonies_corporations.json
5. src/locales/ru/colonies.json
6. src/locales/ru/community_corporations.json
7. **[done]** src/locales/ru/corporations.json
8. src/locales/ru/game_end.json
9. src/locales/ru/help_iconography.json
10. src/locales/ru/log_messages.json
11. src/locales/ru/preferences.json
12. src/locales/ru/prelude_cards.json
13. src/locales/ru/preludes.json
14. src/locales/ru/promo.json
15. src/locales/ru/standard_projects.json
16. src/locales/ru/start_screen.json
17. src/locales/ru/turmoil_cards.json
18. src/locales/ru/turmoil_corporations.json
19. src/locales/ru/turmoil_events.json
20. src/locales/ru/turmoil.json
21. **[in progress]** src/locales/ru/ui.json
22. src/locales/ru/venus_next_cards.json
23. src/locales/ru/venus_next_corporations.json

**Comment by kberg** [comment]
@ainokna how's it going? Been a while since you've picked this up, and still WIP.

**Comment by ltdstudio** [comment]
It is recommended that the flag icon be set to two rows

**Comment by kberg** [comment]
There hasn't been a response in over two months. I'm going to close this, but since you still have a branch you can resubmit the PR, or we can reopen this one when you get back to us.

**Pull request closed without merging**
