### PR TITLE
Improve rending for ms awards ranking

### PR DESCRIPTION
**Pull request by pierrehilbert**
I implemented @ssimeonoff suggestion.

### CODE REVIEW

**Comment by vincentneko** [comment]
@pierrehilbert this is awesome !

**Comment by nwai90** [comment]
This looks great! 👍 

Screenshot 2020-07-24 at 3 51 45 PM

**Comment by pierrehilbert** [comment]
Strange, normally it should be ordered.
Will take a look

**Comment by ssimeonoff** [comment]
Can you add 2 conditions: 
- if a milestone is taken - do NOT show the numbers for it
- if 3 milestones are taken - do NOT show numbers on ANY milestones

Not much of a useful feature, but just to ease the UI a bit.

**Comment by vincentneko** [comment]
> Can you add 2 conditions:
> 
> * if a milestone is taken - do NOT show the numbers for it
> * if 3 milestones are taken - do NOT show numbers on ANY milestones
> 
> Not much of a useful feature, but just to ease the UI a bit.

Already effective ;-)

**Comment by nwai90** [comment]
> Strange, normally it should be ordered.
> 
> Edit: I just tried with 6 players and it's ordered, strange.
> 
> Capture d’écran 2020-07-24 à 10 05 21

@pierrehilbert Yes, it's ordered. The image was an edited one.

**Pull request merged**
