### PR TITLE
Add Big Box promo cards

### PR DESCRIPTION
**Pull request by nwai90**
Rebased against `master`. We can probably merge this after the Kickstarter has closed: https://www.kickstarter.com/projects/strongholdgames/terraforming-mars-big-box

Will add the logs for the new cards afterwards

### CODE REVIEW

**Comment by alrusdi** [comment]
Is there some reasons for this PR to be from your personal repository?
I mean, it is better to merge already checked **bafolts:bigbox_promo** > bafolts:master than  **nwai90:bigbox_promo** > bafolts:master

**Comment by nwai90** [comment]
> Is there some reasons for this PR to be from your personal repository?
> I mean, it is better to merge already checked **bafolts:bigbox_promo** > bafolts:master instead of **nwai90:bigbox_promo** > bafolts:master

The two `bigbox_promo` branches are identical. I rebased against my branch; we can do the same for `bafolts:bigbox_promo` too

**Comment by alrusdi** [comment]
@nwai90 can you please merge your bigbox_promo with current bafolts:bigbox_promo
I've reformated cards.less due to my ignorance while attempting to merge master->bigbox_promo. Sorry

**Comment by nwai90** [comment]
@alrusdi I saw there are hundreds of conflicts 😅 Will close this and raise a new PR from `bafolts:bigbox_promo` to `bafolts:master` instead, it's easier that way.

**Pull request closed without merging**
