### PR TITLE
Initial files for Polish translation

### PR DESCRIPTION
**Pull request by alrusdi**
Base files for Polish translation provided by @Haas888
Discussion: https://github.com/bafolts/terraforming-mars/discussions/2060

### CODE REVIEW

**Review by Haas888 — CHANGES_REQUESTED** [review]
Bigboxpromo.json is not translated and has to be deleted for now

**Comment by alrusdi** [comment]
> Bigboxpromo.json is not translated and has to be deleted for now

I've set all Chinese strings in this file to empty. You can fill them by correct values latter.

**Comment by alrusdi** [comment]
@Haas888 feel free to test your translation here https://tm.alrusdi.ru/debug-ui
You may need to switch to Polish language first here https://tm.alrusdi.ru

**Review by bafolts — APPROVED** [review]

**Comment by sienmich** [comment]
@Haas888 , I couln't find u on Discord, so I'll write here, feel free to add me there for more real time help.

In alrusi's server u can easily see how your translation is working. You can either just look at the cards in /debug-ui or see the logs there in console (Inspect Page in Chrome (Ctrl+Shift+C or Ctrl+Shift+U) -> Console). If some text did not translate, but you have that in your files, then check for some commas, spaces etc., best option will be to copy text from those logs.

It would be the best if you could update those files in this Pull Request directly. If you need help doing this let me know. You could also see how your changes are working online this way.

Thanks for doing this, good job!

**Comment by sienmich** [comment]
@bafolts, do not merge :D

**Comment by Haas888** [comment]
> @Haas888 , I couln't find u on Discord, so I'll write here, feel free to add me there for more real time help.
> 
> In alrusi's server u can easily see how your translation is working. You can either just look at the cards in /debug-ui or see the logs there in console (Inspect Page in Chrome (Ctrl+Shift+C or Ctrl+Shift+U) -> Console). If some text did not translate, but you have that in your files, then check for some commas, spaces etc., best option will be to copy text from those logs.
> 
> It would be the best if you could update those files in this Pull Request directly. If you need help doing this let me know. You could also see how your changes are working online this way.
> 
> Thanks for doing this, good job!

I am a little short on time in the upcoming days, but I'll try to review files and make adjustments soon.

**Pull request merged**
