### PR TITLE
Hover show description over res box

### PR DESCRIPTION
**Pull request by chosta**
+ fix for some cards that could not have their description read because of res box

### CODE REVIEW

**Comment by alrusdi** [comment]
Why do we need it?
We already have something like this when "Magnify card descriptions on hover" option is enabled
sc3
sc1
sc2

**Comment by chosta** [comment]
We were discussing this in discord. A couple of users complained its impossible to read on some cards and we decided that a hover - toggle view would be a good fix. 
I see the benefit of the option for "magnify description" but that is 3 clicks too many to check just a single card. You need to click on options -> select magnify -> read the text -> deselect magnify.
I'm ok with cancelling this change but I also don't see a problem letting it stay as it is set for only ~15 cards and the effect is immediate and intuitive.
@vincentneko @ssimeonoff let us know what you think

**Comment by nwai90** [comment]
If it's only ~15 cards and we know the list of cards, another option might be to rework the css for those cards so that their descriptions are not blocked by the resource counter. That would be visually friendlier for new players as well / those playing with a new expansion for the first few times.

**Comment by chosta** [comment]
@nwai90 It would be very hard for Pharmacy Union for example:
https://ssimeonoff.github.io/cards-list#corp40

**Comment by nwai90** [comment]
> @nwai90 It would be very hard for Pharmacy Union for example:
> https://ssimeonoff.github.io/cards-list#corp40

True, this is an anomaly 🙃

**Comment by chosta** [comment]
So what do we do with this one :) ?

**Review by alrusdi — APPROVED** [review]
let's merge it. My workaround described above is not working for now.

**Pull request merged**
