### PR TITLE
add LeadershipSummit from nwai90/ux_improvements

### PR DESCRIPTION
**Pull request by Ronnoc**

### CODE REVIEW

**Review by kberg — CHANGES_REQUESTED** [review]
Can this become part of the CardManifest instead? In the same way there are two sources of Preludes, this would fit naturally into there.

**Comment by kberg** [comment]
@Ronnoc do you want some help with this?

**Comment by Ronnoc** [comment]
> @Ronnoc do you want some help with this?

Sorry, but I didn't find globalEvents manifest

**Comment by kberg** [comment]
> > @Ronnoc do you want some help with this?
> 
> Sorry, but I didn't find globalEvents manifest

There is no GlobalEventsManifest. I am saying that we would add a new card type to the CardManiffest represnting global events.

Also, it seems every time you force push our prior discussions disappear. Can you find a way to not force push?

**Comment by Ronnoc** [comment]
> > > @Ronnoc do you want some help with this?
> > 
> > 
> > Sorry, but I didn't find globalEvents manifest
> 
> There is no GlobalEventsManifest. I am saying that we would add a new card type to the CardManiffest represnting global events.
> 
> Also, it seems every time you force push our prior discussions disappear. Can you find a way to not force push?

Sorry, I will not force push.

**Review by kberg — APPROVED** [review]
We can always revamp another time.

**Pull request merged**
