### PR TITLE
Added promo card Snow Algae (#539)

### PR DESCRIPTION
**Pull request by gomfunkel**
Includes pull request #569, please merge #569 first.

### CODE REVIEW

**Comment by gomfunkel** [comment]
@alrusdi Done.

**Comment by gomfunkel** [comment]
@alrusdi Yes, my mistake. Should have branched every single card from master instead of the previous card. Shall we close all the pull requests except #569 so I can recreate them or would you prefer rebasing everything (not sure what the effect on existing pull requests is i this case).

**Comment by alrusdi** [comment]
> @alrusdi Yes, my mistake. Should have branched every single card from master instead of the previous card. Shall we close all the pull requests except #569 so I can recreate them or would you prefer rebasing everything (not sure what the effect on existing pull requests is i this case).

Variant with only #569 is ok - but, please, apply all changes that i requested for other PRs

**Comment by gomfunkel** [comment]
@alrusdi Great, I will!

**Comment by alrusdi** [comment]
> @alrusdi Yes, my mistake. Should have branched every single card from master instead of the previous card. Shall we close all the pull requests except #569 so I can recreate them or would you prefer rebasing everything (not sure what the effect on existing pull requests is i this case).

It's okay to apply all review changes to gomfunkel:issue-539-interplanetary-trade branch

**Comment by gomfunkel** [comment]
Closed. Will not be merged.

**Pull request closed without merging**
