### PR TITLE
Simplify Political Agenda API, etc

### PR DESCRIPTION
**Pull request by kberg**
I meant to do this a couple of months ago, but it reduces a bunch of the code based on the interim and original data structures. Still doesn't implement the revised algorithm, but that's just a matter of time.

This simplifies what is serialized and also sent in the model.

I need to manually test the UI still, hence RFC.

### CODE REVIEW

**Comment by kberg** [comment]
I played a sanity round. Seems reasonable.

**Review by nwai90 — APPROVED** [review]
LGTM 👍 Would prefer to merge this in two weeks later as spoken

**Comment by kberg** [comment]
Waiting on merging for two weeks.

**Comment by kberg** [comment]
@nwai90 I'm going to fix merge conflicts and then merge?

**Comment by nwai90** [comment]
> @nwai90 I'm going to fix merge conflicts and then merge?

@kberg Sure, go ahead!

**Pull request merged**
