### PR TITLE
Fix too erly solo game final; #164

### PR DESCRIPTION
**Pull request by alrusdi**

### CODE REVIEW

**Comment by alrusdi** [comment]
> Looking into the code, I think isSoloModeWin function is no longer used.
> Can you please double check ?

It is used in server.ts near 297 line

**Comment by vincentneko** [comment]
> > Looking into the code, I think isSoloModeWin function is no longer used.
> > Can you please double check ?
> 
> It is used in server.ts near 297 line

Ok got it thanks.

If I understand correctly, the solo game could stop before end of gen 12 or 14
Should it be 

`return this.preludeExtension ? this.generation === 12 : this.generation === 14;`

instead of

```
    public isSoloModeWin(): boolean {
      if ( ! this.marsIsTerraformed()) return false;
      return this.preludeExtension ? this.generation <= 12 : this.generation <= 14;
    }
```

**Comment by alrusdi** [comment]
> Should it be
> 
> `return this.preludeExtension ? this.generation === 12 : this.generation === 14;`

I believe it's not. We use this function to detect if user win or lose on the final page. To win player must terraform mars and to do it in less than 14 (12) generations

**Comment by vincentneko** [comment]
> > Should it be
> > `return this.preludeExtension ? this.generation === 12 : this.generation === 14;`
> 
> I believe it's not. We use this function only to detect if user win or lose on the final page. To win player must terraform mars AND to do it in less than 14 (12) generations

Ok my bad

**Pull request merged**
