### PR TITLE
Add Ares to the MIlestone Award selector.

### LINKED ISSUE #2577: Rethinking the Venus Milestone/Award config option
Assuming the Venus Next expansion is enabled. There are two different cases:

**When "Random Ms/As" is disabled:**

... Are we sure that users really mind sticking to the published rules? Being able to uncheck "Venus M/A" is a straight nerf to Morning Star, Celestic, Stormcraft, Titan, and expensive cards that add floaters quickly... none of which really need nerfing.

**When "Random milestones" is enabled:**

... In this case, sticking to the published rule (Venus M/A always included) would just feel too weird, so the cards mentioned above will be weakened. However, the Venus M/A should really *always* be in the pool to choose from – I don't think we need an option to turn them off. And it should always just choose 5 because there is no real reason to need 6. So, the cards are debuffed only in *some* games.

If the behavior was as described above, would we really need the option at all?

Some of the above should apply equally to Ares, it just doesn't have the same 'Ares milestone' config option to get rid of.

### PR DESCRIPTION
**Pull request by kberg**
This doesn't close #2577 but it advances it.

### CODE REVIEW

**Review by bafolts — APPROVED** [review]

**Comment by kberg** [comment]
I rewrote MA Selector to include an initial synergy from the two Ares MAs to all the other MAs based on @nwai90's suggestion.

**Review by bafolts — APPROVED** [review]

**Comment by kberg** [comment]
DAMN, it still doesn't work. MA Selector isn't generating data.
```
Starting server on port 8081
#100
/home/kberg/git/terraforming-mars/build/src/MilestoneAwardSelector.js:257
            throw new Error('No limited synergy milestones and awards set was generated after ' + maxAttempts + ' attempts. Please try again.');
            ^

Error: No limited synergy milestones and awards set was generated after 5 attempts. Please try again.
    at getRandomMilestonesAndAwards (/home/kberg/git/terraforming-mars/build/src/MilestoneAwardSelector.js:257:19)
    at getRandomMilestonesAndAwards (/home/kberg/git/terraforming-mars/build/src/MilestoneAwardSelector.js:277:28)
```

**Comment by kberg** [comment]
image

1,000,000 runs of limited synergy fails 1,525 times, or 00.15%, which means that it will reject ~ once every 655 times

Reducing the default synergy to  4 and 3 result in even worse failures:

4: 2989 errors (!) out of 1 million
3: 6685???

If I remove the default value altogether, there are 0 failures in 1,000,000 runs. Removing the default.

**Review by nwai90 — APPROVED** [review]

**Comment by vsrisuknimit** [comment]
@kberg @nwai90 Could it be that something is changed and now wrong in the selection algorithm?

Here is the old data for why I set the number to 5 to prevent infinite loop. I believe I tried 1 million before and got similar data. 5 times should be more than enough.

https://github.com/bafolts/terraforming-mars/pull/1637#issuecomment-711411034

**Comment by vsrisuknimit** [comment]
Ah, my bad, I see you remove the default value for all milestones, not default value for the 5 try limit. Sorry, only look at the comment, not the code.

**Pull request merged**
