### PR TITLE
Mea culpa, I broke client-side logging

### PR DESCRIPTION
**Pull request by kberg**

### CODE REVIEW

**Review by nwai90 — APPROVED** [review]

**Review by bafolts — APPROVED** [review]

**Comment by bafolts** [comment]
How is it broken? The cards seem to log for me.

**Comment by Lynesth** [comment]
Leaving a note here: talked about it on Discord, but what's broken exactly?
firefox_2020-10-13_12-13-49
firefox_2020-10-13_12-13-35

**Comment by kberg** [comment]
Added a Do Not Merge tag -- others seem to be saying the same thing.

**Comment by kberg** [comment]
Abandoning. I put it in another branch for the time being.

**Pull request closed without merging**
