### PR TITLE
Big push of Ares cards

### PR DESCRIPTION
**Pull request by kberg**
All the cards are defined. All the tiles except hazards are defined. There are empty test suites for all the cards.

Most of the remaining work is listed in TODOs which I will now be working from.
(Though details about oceans and hazards hasn't been marked as TODOs, and will be a significant amount of work in AresHandler.)

### CODE REVIEW

**Comment by kberg** [comment]
(Sorry, wrong base in the PR, fixed.)

**Comment by chosta** [comment]
@kberg is this playable, I'd like to review it but It would be great if I can also test ingame stuff locally

**Comment by vincentneko** [comment]
Build fails with this error  ##[error]src/Dealer.ts(464,38): error TS2307: Cannot find module './cards/ares/BiofertilizerFacility'.

**Comment by kberg** [comment]
> Build fails with this error ##[error]src/Dealer.ts(464,38): error TS2307: Cannot find module './cards/ares/BiofertilizerFacility'.
Yeah, I just sent an update. Amazing how I ran `npm run build ; npm test` and this didn't come up. Lesson is to run `rm -rf dist/` first.

> @kberg is this playable, I'd like to review it but It would be great if I can also test ingame stuff locally
@chosta nah. not yet.

**Comment by kberg** [comment]
Ha! Windows you stink. case-based file renames aren't trivial: https://www.hanselman.com/blog/GitIsCasesensitiveAndYourFilesystemMayNotBeWeirdFolderMergingOnWindows.aspx

**Comment by kberg** [comment]
@chosta actually if you want to try it, make this local change to `Dealer.ts:`

```
export const ALL_ARES_PROJECT_CARDS: Array<ICardFactory<IProjectCard>> = [
    { cardName: CardName.BIOENGINEERING_ENCLOSURE, factory: BioengineeringEnclosure },
    { cardName: CardName.BIOFERTILIZER_FACILITY, factory: BiofertilizerFacility },
//    { cardName: CardName.BUTTERFLY_EFFECT, factory: ButterflyEffect },
    { cardName: CardName.CAPITAL_ARES, factory: CapitalAres },
    { cardName: CardName.COMMERCIAL_DISTRICT_ARES, factory: CommercialDistrictAres },
//    { cardName: CardName.DESPERATE_MEASURES, factory: DesperateMeasures },
    { cardName: CardName.ECOLOGICAL_ZONE_ARES, factory: EcologicalZoneAres },
//    { cardName: CardName.ECOLOGICAL_SURVEY, factory: EcologicalSurvey },
//    { cardName: CardName.GEOLOGICAL_SURVEY, factory: GeologicalSurvey },
    { cardName: CardName.INDUSTRIAL_CENTER_ARES, factory: IndustrialCenterAres },
    { cardName: CardName.LAVA_FLOWS_ARES, factory: LavaFlowsAres },
    { cardName: CardName.MARKETING_EXPERTS, factory: MarketingExperts },
    { cardName: CardName.METALLIC_ASTEROID, factory: MetallicAsteroid },
    { cardName: CardName.MINING_AREA_ARES, factory: MiningAreaAres },
    { cardName: CardName.MINING_RIGHTS_ARES, factory: MiningRightsAres },
    { cardName: CardName.MOHOLE_AREA_ARES, factory: MoholeAreaAres },
    { cardName: CardName.NATURAL_PRESERVE_ARES, factory: NaturalPreserveAres },
    { cardName: CardName.NUCLEAR_ZONE_ARES, factory: NuclearZoneAres },
//    { cardName: CardName.OCEAN_CITY, factory: OceanCity },
//    { cardName: CardName.OCEAN_FARM, factory: OceanFarm },
//    { cardName: CardName.OCEAN_SANCTUARY, factory: OceanSanctuary },
    { cardName: CardName.RESTRICTED_AREA_ARES, factory: RestrictedAreaAres },
    { cardName: CardName.SOLAR_FARM, factory: SolarFarm },
]
```

with these caveats:
1. NuclearZone won't force a cost bonus, or maybe it will? I forget.
2. Solar farm, Metallic Asteroid and Biofertilizer Facility won't have icons.
3. Metallic Asteroid might not decrease plants.
4. The HTML for the cards needs dedicated visual inspection.

**Comment by kberg** [comment]
@chosta if you pull from https://github.com/kberg/terraforming-mars/tree/cards2 then you can play it. Ecological Survey and Geological Survey work, and I have seen in-game success with adjacency bonuses. I'd like to work through all the cards, so I'll do a little running, but yeah, I'll accept feedback.

**Comment by chosta** [comment]
@kberg Great work. I've tried it locally and most of the things do work. There are still a lot of TODO's on your list but I feel like you won't have a problem with them. Didn't find anything obvious with the code although I just skimmed it but we can probably can get @nwai90 + @vincentneko have a quick look and have this merged to ares so we don't leave it hanging. Just to add to your todo - an icon showing that it is a card from the ares expansion would be great. I think we can also help with visualising the special tiles and hazards. Let us know and keep up the good work. Can't wait to try this on beta soon.

**Comment by kberg** [comment]
I wondered about adding an Ares icon. Makes sense. I'll add another TODO.

**Comment by nwai90** [comment]
@kberg Mostly looks good; the TODO comments can be addressed and cleaned up later 👍

**Comment by kberg** [comment]
Thank you. For sure, I'm removing a bunch as they come along.

**Comment by kberg** [comment]
Thank you!

**Pull request merged**
