### PR TITLE
[WIP] Add promo corp Astrodrill

### PR DESCRIPTION
**Pull request by nwai90**
**Ref:** https://www.kickstarter.com/projects/strongholdgames/terraforming-mars-big-box/posts/2867018

image

Screenshot 2020-06-17 at 4 11 46 PM
Screenshot 2020-06-17 at 4 13 58 PM
Screenshot 2020-06-17 at 4 14 35 PM

### CODE REVIEW

**Comment by nwai90** [comment]
@vincentneko This is working fine, but I noticed that the interrupt remains even after resolution: https://github.com/bafolts/terraforming-mars/compare/master...nwai90:astrodrill?expand=1#diff-2f1af24cacc8d39e773be6d9cea1e73dR56.

I saw that this is a similar problem for some other cards like Viral Enhancers as well (manually clearing the interrupt in `tests/cards/ViralEnhancers.spec.ts`). Perhaps we should address these cases together in a separate PR. Do you have any idea about it?

**Comment by vincentneko** [comment]
> @vincentneko This is working fine, but I noticed that the interrupt remains even after resolution: https://github.com/bafolts/terraforming-mars/compare/master...nwai90:astrodrill?expand=1#diff-2f1af24cacc8d39e773be6d9cea1e73dR56.
> 
> I saw that this is a similar problem for some other cards like Viral Enhancers as well (manually clearing the interrupt in `tests/cards/ViralEnhancers.spec.ts`). Perhaps we should address these cases together in a separate PR. Do you have any idea about it?

I don't think we need interrupts with this card. The could `addResource  `or `addResourceToSelf`  could return `gainStandardResource `instead of `undefined`.

**Comment by nwai90** [comment]
> > @vincentneko This is working fine, but I noticed that the interrupt remains even after resolution: https://github.com/bafolts/terraforming-mars/compare/master...nwai90:astrodrill?expand=1#diff-2f1af24cacc8d39e773be6d9cea1e73dR56.
> > I saw that this is a similar problem for some other cards like Viral Enhancers as well (manually clearing the interrupt in `tests/cards/ViralEnhancers.spec.ts`). Perhaps we should address these cases together in a separate PR. Do you have any idea about it?
> 
> I don't think we need interrupts with this card. The `addResource `or `addResourceToSelf` methods could return `gainStandardResource `instead of `undefined`.

True, I updated

**Comment by jijiqw** [comment]
The corporation card Astrodrill  is  a little illegible on kickstart , some  words are covered by " PROMO "  . Could you  please tell me where  I can  find a  clear version?

**Comment by nwai90** [comment]
> The corporation card Astrodrill is a little illegible on kickstart , some words are covered by " PROMO " . Could you please tell me where I can find a clear version?

I can't find a clear version as well, this is my best guess based on the iconography and others' comments in the Kickstarter thread

**Pull request merged**
