### PR TITLE
Update russian translation of the cards

### PR DESCRIPTION
**Pull request by alrusdi**

### CODE REVIEW

**Comment by ltdstudio** [comment]
same date to update translation :)

**Comment by alrusdi** [comment]
> same date to update translation :)

You are encouraged me to do it!

**Comment by alrusdi** [comment]
Woohoo! Just noticed that i've got the **3k get** :-)

**Comment by bafolts** [comment]
Remarkable to reach 3000!

**Review by bafolts — APPROVED** [review]

**Comment by ltdstudio** [comment]
> You are encouraged me to do it!

go go go and start moon expansion work

**Pull request merged**
