### PR TITLE
Use visually consistent icons for Ares MAs

### PR DESCRIPTION
**Pull request by nwai90**
Before:
Screenshot 2021-07-01 at 3 37 56 PM

After:
Screenshot 2021-07-01 at 4 09 58 PM

### CODE REVIEW

**Review by alrusdi — APPROVED** [review]

**Comment by kberg** [comment]
Why does the email version have what looks like hazard tiles? I was so confused!

**Comment by nwai90** [comment]
> Why does the email version have what looks like hazard tiles? I was so confused!

@kberg I uploaded the wrong icons at first (with hazard tiles) and replaced them later :D

**Comment by kberg** [comment]
This is one of the many small visual changes I thought, "What I've done is
good enough and someone will come along and fix it eventually." Mission
accomplished! (Thank you!)

>

**Comment by bafolts** [comment]
This looks great!

**Pull request merged**
