### PR TITLE
Miners ON Strike

### PR DESCRIPTION
**Pull request by sauloachkar**

### CODE REVIEW

**Comment by kberg** [comment]
This won't work because it breaks all current games that will look for the previously-spelled card name. Look at `src/deck/Deck.ts` and `tests/deck/Deck.spec.ts`. This is why I said it was not trivial on the discord.

**Comment by kberg** [comment]
If you mimic what those do for global event cards, you should be okay.

**Comment by sauloachkar** [comment]
Don't think I can achieve this yet. Thanks for the heads up

**Comment by kberg** [comment]
Understood! One step at a time.

**Pull request closed without merging**
