### PR TITLE
Move buffer gas out of Prelude Manifest

### LINKED ISSUE #2788: Buffer Gas SP availability should depend only on TR63 mode, not expansions
There's no connection between TR63 mode and the Prelude expansion, or between the Buffer Gas standard project and the Prelude expansion.

It just happened that these rules appear physically in the Prelude rulebook, but this fact is of no consequence.

Currently (as reported by Kowal on discord), the SP is missing when Prelude isn't in use.

### PR DESCRIPTION
**Pull request by vsrisuknimit**
This PR can close #2788 . It allows buffer gas to be available when Prelude is not used, as long as 63TR mode is on.

### CODE REVIEW

**Review by kberg — APPROVED** [review]
This makes sense in retrospect.

**Comment by sienmich** [comment]
Just pointing out it's against the official rules (where `Buffer Gas` was introduced in Prelude expansion). Still, good for me.

**Review by sienmich — APPROVED** [review]

**Comment by vsrisuknimit** [comment]
> Just pointing out it's against the official rules (where Buffer Gas was introduced in Prelude expansion). Still, good for me.

@sienmich see #2788

**Comment by sienmich** [comment]
> @sienmich see #2788

Ok!

**Pull request merged**
