### PR TITLE
Move content type detection to a central location.

### PR DESCRIPTION
**Pull request by kberg**

### CODE REVIEW

**Review by bafolts — CHANGES_REQUESTED** [review]
We make 50-60 network requests on some pages for assets. On a page refresh the server will end up looking through `CONTENT_TYPES` array 50-60 times. I think we should update `CONTENT_TYPES` to be a `Map`. If you map `.map` to `text/javascript` then passing in everything from the last `.` character to the end of the string can be used to look up the content type. This will be much more efficient.

**Comment by kberg** [comment]
> We make 50-60 network requests on some pages for assets. On a page refresh the server will end up looking through `CONTENT_TYPES` array 50-60 times. I think we should update `CONTENT_TYPES` to be a `Map`. If you map `.map` to `text/javascript` then passing in everything from the last `.` character to the end of the string can be used to look up the content type. This will be much more efficient.

You're probably right, but given the rest of the work done that sounds like premature optimization, you see what I mean? I mean, once you're doing a series of string operations just to get to this point in the call, is this really that much of a loss?

But ... OK. It's not as if this optimization makes things harder to read or anything. Will do.

**Comment by bafolts** [comment]
@kberg we have been working together on this long enough I knew as I wrote my requested change that you would be able to talk me out of it :-)

You are right that it is early optimization. I can mark this as approved and if you feel like changing to map that is fine.

**Review by bafolts — APPROVED** [review]

**Comment by kberg** [comment]
> @kberg we have been working together on this long enough I knew as I wrote my requested change that you would be able to talk me out of it :-)
> 
> You are right that it is early optimization. I can mark this as approved and if you feel like changing to map that is fine.

Nah. You conviced ME. The only reason it didn't arrive earlier is that I'm writing a good test.

**Review by bafolts — APPROVED** [review]

**Pull request merged**
