### PR TITLE
Move cards out of Dealer and into CardManifests.

### PR DESCRIPTION
**Pull request by kberg**
This clarifies the code structure and localizes some common behavior across the entire codebase.

This supercedes #1317 which was too much of a mess,  @vincentneko. While I manually verified 1317, I haven't verified this one.

### CODE REVIEW

**Comment by kberg** [comment]
>  While I manually verified 1317, I haven't verified this one.
... yet. :D

**Comment by bafolts** [comment]
I will give this another pass through tomorrow. Looks great on surface.

On a completely unrelated topic I was surprised to see `var` used. I need to add both `no-var` and `prefer-const`.

https://eslint.org/docs/rules/no-var
https://eslint.org/docs/rules/prefer-const

**Comment by kberg** [comment]
Agree.

>

**Comment by kberg** [comment]
So this PR is about 20 days old if you include the original PR which I had to abandon (nobody's fault but my own.) Is it too much to ask for a closer look at it?

**Review by bafolts — APPROVED** [review]
I somehow lost track of this PR, sorry. Looks great! I didn't verify each card moved to the right module but the separation is nice.

**Pull request merged**
