### PR TITLE
Update game board with new icons and making Venus track removable

### PR DESCRIPTION
**Pull request by vsrisuknimit**
1) Update the graphics. Now use new icons. @ssimeonoff 
2) Remove Venus track when Venus expansion is not in used.
3) Adjust the margin to make sure Maxwell base is not cut off.

With Venus
image

Without Venus
image

### CODE REVIEW

**Comment by vsrisuknimit** [comment]
With a lot of help from very patient @chosta

**Comment by kberg** [comment]
Oh! Thank you!

**Comment by kberg** [comment]
Don't let this stop you, but Maxwell base could go, too.

**Comment by alrusdi** [comment]
Isn't id already done by @ssimeonoff ?

**Comment by ssimeonoff** [comment]
No, the previous pr was for the global params in the side bar.

**Review by alrusdi — APPROVED** [review]

**Pull request merged**
