### PR TITLE
help page ui improvement

### PR DESCRIPTION
**Pull request by vsrisuknimit**
- Upgrade the help page, add many more icons
- Align the global parameters now
- Resize and align many icons
- Sublabels
- Flex table working properly
- Clean commit PR

image

### CODE REVIEW

**Comment by vsrisuknimit** [comment]
@chosta @alrusdi clean PR now. I managed not to delete everything.

**Comment by Lynesth** [comment]
Nice looking page :D

Could please you add the `v-i18n` directive to the labels so that we can translate them ?

**Comment by vsrisuknimit** [comment]
@Lynesth just like this? Do I need to import anything? `<div class="help-page-label" v-i18n>Space</div>`

**Comment by vsrisuknimit** [comment]
Added

**Review by alrusdi — APPROVED** [review]

**Pull request merged**
