### PR TITLE
move src/cards to src/cards/base

### PR DESCRIPTION
**Pull request by bafolts**
Self-explanatory. Moves all base cards to the `src/cards/base` directory. No other changes included.

### CODE REVIEW

**Comment by bafolts** [comment]
This is hard to review with the github UI. Below is diff file from CLI.

[easier.txt](https://github.com/bafolts/terraforming-mars/files/5599824/easier.txt)

**Comment by kberg** [comment]
This is a great idea, but since Dani is in the middle of moving all those other files, how can these be done without merge conflict issues?

**Comment by bafolts** [comment]
git mv was used to move the files so there should be no conflicts unless
the same parts of files were changed.

**Comment by kberg** [comment]
> git mv was used to move the files so there should be no conflicts unless the same parts of files were changed.
Fantastic. Looks great. Thank you!

**Review by kberg — APPROVED** [review]

**Pull request merged**
