### PR TITLE
Venus Next WGTerraforming

### PR DESCRIPTION
**Pull request by zx2uther**
added ability to disable WG Terraforming on game setup page

### CODE REVIEW

**Comment by vincentneko** [comment]
I'm currently working on this one, I've taken the issue this morning.

**Comment by alrusdi** [comment]
@vincentneko feel free to finish your PR. It's me asked for this :-(

**Comment by vincentneko** [comment]
> @vincentneko feel free to finish your PR. It's me asked for this :-(

Ok lets do this, this one was hanging for too long !

**Comment by vincentneko** [comment]
Duplicate

**Pull request closed without merging**
