### PR TITLE
Remove card not found warning for now

### PR DESCRIPTION
**Pull request by Lynesth**

### CODE REVIEW

**Comment by kberg** [comment]
Why bother doing this for now?

>

**Comment by chosta** [comment]
Because it's slowing the app because of a great amount of console.warn. Example:
Searching in debug-ui shows 30k warnings since it tries to rerender every element of every card (this is a Vue / React thing actually but console.warn is doing a lot of damage)

**Comment by kberg** [comment]
Well that's a good reason.

>

**Review by kberg — APPROVED** [review]
Approve modulo the change I just suggested.

**Pull request merged**
