### PR TITLE
Have input selection use playerView

### PR DESCRIPTION
**Pull request by kberg**
Depends on #3563 and #3564

Rather than rename all the fields in all the components at once, this commit uses computed to ease the transition. Then I can do the change for each one individually. But these have to be in a bunch because there's a cross-reference between them thanks to the relationship between PlayerInputFactory, AndOptions and OrOptions.

### CODE REVIEW

**Review by nwai90 — APPROVED** [review]
Approved, but please verify that a 2-player game with some cards that invoke `AndOptions` and `OrOptions` can run to the end and render correctly

**Comment by kberg** [comment]
Will do.

**Comment by kberg** [comment]
Dang, wow, nope. New issues. Manual testing now.

**Comment by kberg** [comment]
For the record, I did run this through a game, but I suspect recent changes got in the way. Let's see.

**Pull request merged**
