### PR TITLE
Global params revamp; #684

### PR DESCRIPTION
**Pull request by alrusdi**
YA attempt to make compact global parameters
More translations for colonies
Highlight hint for SelectSpace action
Снимок экрана от 2020-06-04 22-15-32
Снимок экрана от 2020-06-04 22-16-35

### CODE REVIEW

**Comment by vincentneko** [comment]
This looks awesome ! 
Will give it a try by tomorrow and review as well.

**Comment by vincentneko** [comment]
@alrusdi 
Shit I've messed up this branch, I'm sorry. I wanted to merge this branch on the master branch of my repo, I've done the opposite.
Not sure how I can fix this.

**Comment by alrusdi** [comment]
No problem) I will make another PR

**Comment by vincentneko** [comment]
Thanks

**Pull request closed without merging**
