### PR TITLE
Optimized log panel (#428)

### PR DESCRIPTION
**Pull request by gomfunkel**
Implemented the following enhancement ideas from #428:

* Using player colors
* Using card type colors and font
* Added log message when ending turn
* Added log message on new generation

See issue #428 for screenshots and details.

I am not totally happy with the amount of code this requires. If someone has a better idea on how to solve this, please let me know.

### CODE REVIEW

**Comment by gomfunkel** [comment]
@alrusdi The formatting is actually done in the frontend (`LogPanel.ts`). The backend only adds the semantics (in form of html/xml tags), this is required to enable formatting. 

The log messages are rather arbitrary and don't follow a precise pattern (0-n players being mentioned in different places, 0-n cards being mentioned in different places, etc.). I'm not sure if it's better to solve this with a LogMessage interface or similar, at least I don't have a clear image in mind how the interface should look. Do you have a good idea?

It is likely possible to get rid of the `name` attribute and only rely on the `innerHTML` of the `log*` tags to make it more readable, though. Would that already help?

**Comment by alrusdi** [comment]
> The backend only adds the semantics (in form of html/xml tags), this is required to enable formatting.
Why not to add this semantics in json format not html/xml tags?
So each log message can be represent with json like this:
```
{
    "type": "card_played",
    "text": "{} played {}"
    "args": [{"id": "123", "title": "player1"}, {"id": "01", "title": "Colonizer Training Camp"]
}
```
And Log component can render each message type differently (by using "if" statement inside template or even other components)

**Comment by gomfunkel** [comment]
Looks like the responses could be a bit large regarding byte size but I do see the advantages in the interface approach as well. Using an interface it would definitely be more easy to add additional information/metadata (timestamps for example).

Any other opinions on this?

**Comment by alrusdi** [comment]
> Any other opinions on this?
Optimization by response size should be considered latter. We can gzip it, or split requests as necessary. Premature optimization is the root of all evil ;-)

**Comment by bafolts** [comment]
I think this approach is fine. If for whatever reason the size did prove to be an issue changing it to a JSON object later should not be difficult. This approach here is at least simple. If we were to use some JSON object we would only be making our own data structure which represented a vue.js template anyway. That being said, with this approach we will need to escape any values we put inside `""` or `><` or we would have invalid XML. That is the downside of this approach. If using JSON we wouldn't have to do this escaping, we would only need put into a JSON object, call `JSON.stringify` and then `JSON.parse` inside the log component on the client side. Escaping the string and the XML will require two functions which are not straight forward.

By the time I finished writing that paragraph I have talked myself into wanting to serialize to some `LogModel` JSON object that we pack on the server and then the component uses the `LogModel` to create the vue templates it needs. This will avoid us having to escape the data for the Vue.js template.

**Comment by alrusdi** [comment]
> By the time I finished writing that paragraph I have talked myself into wanting to serialize to some `LogModel` JSON object that we pack on the server and then the component uses the `LogModel` to create the vue templates it needs. This will avoid us having to escape the data for the Vue.js template.

It is exactly what i want. Of course i think about i18n too. It is much easier to translate base message + params than one big blackbox string.

**Comment by gomfunkel** [comment]
OK, got it. Will introduce a model for the log (messages) and update this pull request as soon as I'm done.

**Comment by gomfunkel** [comment]
Refactored the game logging according to our discussion, @bafolts and @alrusdi.

**Comment by alrusdi** [comment]
@gomfunkel can you please merge upstream master branch into your branch?

**Comment by gomfunkel** [comment]
@alrusdi Conflicts resolved.

**Comment by alrusdi** [comment]
I like this version. I can try translate all the messages into Russian after merge and check if this logging work for us perfectly

**Pull request merged**
