### PR TITLE
Add one-time alert when Mars is terraformed

### PR DESCRIPTION
**Pull request by nwai90**
**Ref:** https://github.com/bafolts/terraforming-mars/issues/777

- Show an alert only once when Mars is fully terraformed
- Don't show the alert on game_end screen
- Basic alert for now, in future this can be a nicer styled onscreen animation with sound

Screenshot 2020-06-30 at 6 48 56 PM

### CODE REVIEW

**Comment by alrusdi** [comment]
@nwai90 Can you please make an option (enabled by default) for it in Preferences dialog?

**Comment by nwai90** [comment]
> @nwai90 Can you please make an option (enabled by default) for it in Preferences dialog?

@alrusdi Sure, I can add it. Do we want to introduce a preference option for this though? As it is just one alert throughout the entire game.

Screenshot 2020-06-30 at 9 03 01 PM

**Comment by alrusdi** [comment]
@nwai90 i don't know. It will be little annoying to me personally. If it is not hard to do - please do it :-)

**Comment by nwai90** [comment]
> @nwai90 i don't know. It will be little annoying to me personally. If it is not hard to do - please do it :-)

@alrusdi Done, I added the option to PreferencesManager

**Pull request merged**
