### PR TITLE
Fix Mars-pattern baldness

### PR DESCRIPTION
**Pull request by vsrisuknimit**
- Remove the blank space above when Venus is not in used.
- Move Stanford Torus to the top

What I would like to do:
- Conditional placement for Stanford Torus. Move it to the right when Venus next is not in used. I do not know how to do that yet.

Screen Shot 2020-10-06 at 9 14 45 AM

Screen Shot 2020-10-06 at 9 15 01 AM

### CODE REVIEW

**Comment by alrusdi** [comment]
I don't like it >< May be it is better to keep Venus bar but grey-out it and add little transparency?

**Comment by vsrisuknimit** [comment]
Does it weird without Venus track? @alrusdi

**Comment by alrusdi** [comment]
> Does it weird without Venus track? @alrusdi

To me it is little strange. Can we try gray-outed version? I will provide a demo

**Comment by chosta** [comment]
> To me it is little strange. Can we try gray-outed version? I will provide a demo

I second greyed out version

**Comment by vsrisuknimit** [comment]
With Venus

image

Without Venus

image

@chosta @alrusdi

**Review by alrusdi — APPROVED** [review]

**Pull request merged**
