### PR TITLE
experimental forest: draw first

### PR DESCRIPTION
**Pull request by vsrisuknimit**
Now it draws two plant tag cards first.

I am not sure how to reverse the log order.

image

### CODE REVIEW

**Comment by vsrisuknimit** [comment]
This PR closes #1692 .

**Review by nwai90 — APPROVED** [review]
Perhaps remove the two comments - should not be necessary

**Comment by kberg** [comment]
> Now it draws two plant tag cards first.
> 
> I am not sure how to reverse the log order.
> 
> image

In the code where you log the forests, add // TODO(kberg): make it log the card play first.

**Comment by vsrisuknimit** [comment]
removed comments, added todo for @kberg .
The order should be:

You played Experimental Forest.
You drew X and Y.

**Pull request merged**
