### PR TITLE
rename tradeThisTurn

### PR DESCRIPTION
**Pull request by vsrisuknimit**
The only thing this PR does is renaming player.tradesThisTurn to player.tradesThisGeneration. The variable was badly named since it counts how many times the trade happened this Generation, not Turn as it said.

It does not do much now. But it will be helpful for rebalancing in the future if we actually want to limit the number of trade per Turn, not per Gen.

Tested. Everything works fine. I renamed all instances that I found by searching.

### CODE REVIEW

**Comment by vsrisuknimit** [comment]
@nwai90 pointed out this break existing games due to serialization shenanigans, so let's close this for now. But we should consider renaming it when we are merging other things such as renaming card names #2839 that will also break existing games.

**Comment by kberg** [comment]
The card name renames shouldn't be breaking existing changes given how
Brian recently did it. Same here, this is easy to fix without breaking
existing games. I'll kick that off.

**Review by kberg — COMMENTED** [review]
Also you can revive this PR and do everything you did except rename the SerializedPlayer, and leave that as as TODO.

**Comment by vsrisuknimit** [comment]
@kberg I reopened. 

`did except rename the SerializedPlayer, and leave that as as TODO`

Don't think I understand this part.

**Comment by kberg** [comment]
> @kberg I reopened.
> 
> `did except rename the SerializedPlayer, and leave that as as TODO`
> 
> Don't think I understand this part.

The short version is to roll back the change to SerializedPlayer. That means that the serialize and deserialize functions will look a little weird: in serialize, you'll assign tradesThisGeneration to tradesThisTurn, and in deserialize you'll assign tradesThisTurn to tradesThisGeneration. And that'll look peculiar and doesn't fully do what you wanted, but the next part, which slowly changes what the field is stored as in the database, I'll do for you.

Does that explain it? If not, just say OK, and I'll make a commit that demonstrates it.

**Comment by vsrisuknimit** [comment]
@kberg please take a look. The test failed due to deserialization. I am not sure how to fix that one.

**Comment by kberg** [comment]
Will do. I hate that test that's breaking right now, but it's a good one.

**Review by kberg — COMMENTED** [review]
I removed the test, and added another brief expectation in the test below.

That particular test is good but brittle, and was written before we had more carefully rewritten how serialization goes. It doesn't help when trying to rename things, so it's fine to remove it.

**Review by kberg — APPROVED** [review]

**Pull request merged**
