### PR TITLE
Can you develop a funtion(Entrance) for Spectator?

### PR DESCRIPTION
**Pull request by ltdstudio**
hi , all developer. Thank you for still updating.  We play this game  so long. and we want learning skill form my other friend game match. So, can you develop a funtion for game watch ?
Thanks again.

### CODE REVIEW

**Comment by chosta** [comment]
Hello and welcome!
Yes a spectator mode is coming soon. We will keep you updated.
Please, ask your questions or propose features in the [issues](https://github.com/bafolts/terraforming-mars/issues) section next time. I'll close this pull request as I don't see anything meaningful codewise.

**Comment by ltdstudio** [comment]
thanks a lot, I take it. and I want translate something to Chinese, please
give some permissions if you want.

Danimir <notifications@github.com> 于2020年12月2日周三 下午9:41写道：

**Comment by bafolts** [comment]
@ltdstudio your Chinese translations would be appreciated! With git access is given on an entire repository basis and not per file or directory. For the host repository which happens to be `bafolts` contributors who have been contributing for some time are given write access for simplicity of some tasks. Nothing is stopping anyone from forking and providing a pull request from a fork. For this situation if you fork the repository and modify the chinese translations you can then create a pull request from that fork. You could also post the translations with English and Chinese in an issue and we can work that into the translations file for you. Also feel free to email me the translations and I can put them up as an issue.

**Comment by ltdstudio** [comment]
ok, I'll do it as soon.


Brian Folts <notifications@github.com> 于2020年12月3日周四 下午11:00写道：

**Pull request closed without merging**
