### PR TITLE
Use playerId for log messages (#496)

### PR DESCRIPTION
**Pull request by gomfunkel**
Fixed issue #496 to always use the correct player color. Also includes the fix from pull request #521 regarding the missing colony name.

Please check if this exposes the `playerId` in a way we don't want to.

### CODE REVIEW

**Comment by alrusdi** [comment]
I don't sure if we really need this. It is better to validate CreateGame form to disallow identical names and colors for players.

**Comment by alrusdi** [comment]
@gomfunkel please resolve conflicts with current upstream branch and we will merge your PR

**Comment by FreeLikeGNU** [comment]
> ... I don't want to tell people they can't play if they have the same name.

Especially if their names happen to be "Bruce"!

**Comment by gomfunkel** [comment]
@alrusdi Done!

**Pull request merged**
