### PR TITLE
Remove explicit types on cards.

### PR DESCRIPTION
**Pull request by kberg**
Here is some evidence this doesn't seem to put type safety at risk:

I changed a line of code in `Capital.ts`

`public cardType = 100; // CardType.AUTOMATED;`

The compiler wasn't having any of it.

```
src/cards/Capital.ts:3:1 - error TS6133: 'CardType' is declared but its value is never read.

3 import {CardType} from './CardType';
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/cards/Capital.ts:18:12 - error TS2416: Property 'cardType' in type 'Capital' is not assignable to the same property in base type 'IProjectCard'.
  Type 'number' is not assignable to type 'CardType'.

18     public cardType = 100; // CardType.AUTOMATED;
              ~~~~~~~~

src/cards/StandardCardManifests.ts:248:39 - error TS2322: Type 'typeof Capital' is not assignable to type 'new () => IProjectCard'.
  Construct signature return types 'Capital' and 'IProjectCard' are incompatible.
    The types of 'cardType' are incompatible between these types.
      Type 'number' is not assignable to type 'CardType'.

248         { cardName: CardName.CAPITAL, factory: Capital },
                                          ~~~~~~~

  src/cards/ICardFactory.ts:6:5
    6     factory: new () => T;
          ~~~~~~~
    The expected type comes from property 'factory' which is declared here on type 'ICardFactory<IProjectCard>'

src/cards/ares/AresCardManifest.ts:34:44 - error TS2322: Type 'typeof CapitalAres' is not assignable to type 'new () => IProjectCard'.
  Construct signature return types 'CapitalAres' and 'IProjectCard' are incompatible.
    The types of 'cardType' are incompatible between these types.
      Type 'number' is not assignable to type 'CardType'.

34         { cardName: CardName.CAPITAL_ARES, factory: CapitalAres },
                                              ~~~~~~~

  src/cards/ICardFactory.ts:6:5
    6     factory: new () => T;
          ~~~~~~~
    The expected type comes from property 'factory' which is declared here on type 'ICardFactory<IProjectCard>'


Found 4 errors.
```

### CODE REVIEW

**Comment by kberg** [comment]
That's a lot of files, but I think they're easy to review because they look the same. I can split this into clusters of 100, perhaps.

**Comment by bafolts** [comment]
No worries. I will scan through quickly. Typescript is still checking here for us.

**Review by bafolts — APPROVED** [review]
Manually went through each change in local diff. Didn't spot any issues.

**Comment by kberg** [comment]
Thanks

**Pull request merged**
