### PR TITLE
Move game.getSpace to board.getSpace where it belongs.

### PR DESCRIPTION
**Pull request by kberg**
This makes it available for Board subclasses, (like MoonBoard!)

### CODE REVIEW

**Comment by kberg** [comment]
How is this breaking? The bad line referenced isn't even appropriate. I've built in a clean workspace and it builds.

**Comment by nwai90** [comment]
@kberg Not entirely sure about the issue but I had a hunch. I added a step to remove existing build folder prior to building and it seems to help: https://github.com/nwai90/terraforming-mars/commits/spaceid

**Comment by kberg** [comment]
Huh!

**Comment by kberg** [comment]
@nwai90 nope. :/ I'm heading to bed.

**Comment by nwai90** [comment]
Yeah, doesn't help. Might be a CI-environment related issue

**Comment by kberg** [comment]
Closing in favor of #2318

**Pull request closed without merging**
