### PR TITLE
Move CreateGameForm to SFC

### PR DESCRIPTION
**Pull request by kberg**
Still needs some work, but I'm licking the cookie.

### CODE REVIEW

**Review by bafolts — CHANGES_REQUESTED** [review]
When I run this locally I see warnings logged to the console.

```
vue.esm.js:628 [Vue warn]: Duplicate keys detected: '1'. This may cause an update error.

found in

---> <CreateGameForm> at src/components/create/CreateGameForm.vue
       <Root>
```

Should address these warnings before merging.

**Comment by kberg** [comment]
> When I run this locally I see warnings logged to the console.
> 
> ```
> vue.esm.js:628 [Vue warn]: Duplicate keys detected: '1'. This may cause an update error.
> 
> found in
> 
> ---> <CreateGameForm> at src/components/create/CreateGameForm.vue
>        <Root>
> ```
> 
> Should address these warnings before merging.

Oh, good catch.  Sorry - I usually leave my console open.

**Comment by bafolts** [comment]
Something is off with the color selection for multiple players:

before:

image

after:

image

**Comment by kberg** [comment]
Oh this is interesting. This is due to adding the <div> to support v-bind.
OK I'll have to dig into this.

>

**Comment by kberg** [comment]
> Oh this is interesting. This is due to adding the <div> to support v-bind. OK I'll have to dig into this.
> […](#)

OK, PTAL.

**Review by bafolts — APPROVED** [review]

**Pull request merged**
