### PR TITLE
Fixes Tactician milestone

### PR DESCRIPTION
**Pull request by sienmich**
Fixes Tactician milestone and removes unnecesarry `hasRequirements` attribute from IProjectCard

### CODE REVIEW

**Comment by sienmich** [comment]
Closes https://github.com/bafolts/terraforming-mars/issues/2443

**Comment by kberg** [comment]
I'm going to ask Brian to review this, since static card properties are his area of expertise, and I've already expressed concern about the way card properties and metadata are commingling, so I'd rather just stay out of this one

**Review by nwai90 — APPROVED** [review]
Functionally I believe this works fine. I have similar concerns to @kberg in that basing Tactician and CuttingEdgeTechnology's checks on having requirements in a card's metadata conflates business logic with UI rendering logic.

That said as long as we ensure that any new card(s) with real requirements added always have a `requirements` attribute in metadata it should be ok 👍

**Comment by sienmich** [comment]
> That said as long as we ensure that any new card(s) with real requirements added always have a `requirements` attribute in metadata it should be ok.

Well, right now that's the only place to put the requirements (except the card description), so it will be hard to miss.
I understand the 'mixing UI and functionalities' concern.

Should I move the `requirements` from metadata to card itself? Maybe this would improve the readability?

**Comment by nwai90** [comment]
@sienmich It is generally fine for me since the logic is still quite clear, let's see what others think about it

**Comment by kberg** [comment]
> Functionally I believe this works fine. I have similar concerns to @kberg in that basing Tactician and CuttingEdgeTechnology's checks on having requirements in a card's metadata conflates business logic with UI rendering logic.
> 
> That said as long as we ensure that any new card(s) with real requirements added always have a `requirements` attribute in metadata it should be ok

Here are my concerns: first, this PR isn't really about fixing the tactician milestone, it's about restructiring the code. Which is fine, for sure.  

In another PR you can see the effect of this change, which incldues this line:

```
  if (this.properties.metadata.requirements?.satisfies(player) === false) {
```

This is **metadata**, which means it should store **data**. But this is **behavior** and so does not belong in metadata.

Finally, I'm reading tactician, and it has this line:

```
const hasRequirements = card.canPlay && (card.hasRequirements === undefined || card.hasRequirements);
```

It's not clear why `card.canPlay` is a prerequisite. A comment describing what this line is doing would be helpful.

**Comment by Lynesth** [comment]
@kberg Because that code is a bit... meh.
Instead of having a simple `hasRequirements = true` for Tactician, it's actually checking if the card has a `canPlay` method.
Then, it assumes that it is a card with requirements, unless it has a `hasRequirements = false`.

**Comment by kberg** [comment]
It's possible, I was reading from my VSCode instance.

**Comment by kberg** [comment]
My first message was a little brusque, because I was trying to get back to the first PR which included the line that helped me see the concernse I had with the first one. So first, thanks for the fix, for certain. But also, please think about how you can move behavior out of metadata. Not now, but eventually.

**Comment by sienmich** [comment]
@kberg 

> Finally, I'm reading tactician, and it has this line:
> 
> ```
> const hasRequirements = card.canPlay && (card.hasRequirements === undefined || card.hasRequirements);
> ```
> 
> It's not clear why `card.canPlay` is a prerequisite. A comment describing what this line is doing would be helpful.

Yep, that's the old version, the one I simplified to `const hasRequirements = card.metadata.requirements !== undefined;`, much cleaner imo.

> this PR isn't really about fixing the tactician milestone

It is. To fix the tactician I had to make the change described above. (Because earlier I deleted some `canPlay` methods, which were automaticly calculated from the metadata.requirements; my fault not thinking about the tactician, sry).
And now since the `hasRequirements` was unused, I deleted it.

> This is metadata, which means it should store data. But this is behavior and so does not belong in metadata.

Agree, I'll move the requirements level up, to the card soon.

**Comment by kberg** [comment]
> > this PR isn't really about fixing the tactician milestone
> 
> It is. To fix the tactician I had to make the change described above. (Because earlier I deleted some `canPlay` methods, which were automaticly calculated from the metadata.requirements; my fault not thinking about the tactician, sry).
> And now since the `hasRequirements` was unused, I deleted it.

Sorry, I said the wrong thing here. I did mean that it was such a surprise that the meat of this was moving data around, and it wasn't clear what was going on. That comment about "because earler I deleted some 'canPlay' methods" is really useful and I think would have helped me dive in to review this. But no big deal, it's not as if I don't make mistakes (I make A LOT OF THEM.)

**Pull request merged**
