### PR TITLE
Better ImportedNitrogen #49

### PR DESCRIPTION
**Pull request by bafolts**
Implemented the canPlay method from being a tautology to checking if there are cards which can have the resources needed added to them.

### CODE REVIEW

**Comment by alrusdi** [comment]
This fix seems to be incorrect. It's not REQUIRED to have ability to place Microbes and Animals to another cards it is an option. Rules page 9:
You may play a card that...
...
-  adds  resources  that  you  can’t  collect  (for  example  adding   microbe   resources   without   having   any   microbe   project to place them on).

**Comment by alrusdi** [comment]
I believe, both "SelectCard" actions must be optional and we need to show these options only if someone is already played an applicable cards

**Comment by vincentneko** [comment]
I second this

**Comment by bafolts** [comment]
I updated the card logic so that a player is only presented with options that make sense. If they have no applicable cards they are only given the terraform rating and plants.

**Pull request merged**
