### PR TITLE
Debug UI tweaks

### PR DESCRIPTION
**Pull request by alrusdi**
1) Delay page refresh when user is typing in search box
2) Ability to pass search string parameter via url like this: `/debug-ui?search=ai central`

### CODE REVIEW

**Review by kberg — APPROVED** [review]
Thanks for both of these.

**Comment by kevinb9n** [comment]
Hey @alrusdi, it's now happening that if I type a little too fast in the search box, some letters are getting erased/overtyped. Could that have been introduced with this change?

**Comment by bafolts** [comment]
This is triggering only with the onkeyup event. If you were to type and then hold down a key I would think you could create the problem @kevinb9n sees. Using the onchange event may prove more reliable.

**Comment by kberg** [comment]
That makes a lot of sense. onchange also supports behavior like pasting
into the text box.

>

**Comment by alrusdi** [comment]
> Hey @alrusdi, it's now happening that if I type a little too fast in the search box, some letters are getting erased/overtyped. Could that have been introduced with this change?

Shurely it is. I will try to fix it ASAP

**Pull request merged**
